# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: kongo
dist: ./build
before:
  hooks:
    - make clean
    - make configure
builds:
  - main: ./cmd/kongo/main.go
    binary: kongo
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
    ldflags: -X main.version={{.Version}} -extldflags "-static" -w -s
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: osx
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  vendor: kongo
  homepage: http://fabiosribeiro.com.br
  maintainer: Fábio Ribeiro <fabiorphp@gmail.com>
  description: Manage Kong instances by CLI
  license: MIT
  formats:
    - deb
    - rpm
