dist: trusty
language: go
go:
  - "1.10"
  - master
addons:
  apt:
    packages:
      - rpm

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - make depend
  - make configure

script:
  - make lint
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
