---
version: "3"

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  migration:
    image: kong:0.13.1-alpine
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
    command: kong migrations up

  kong:
    image: kong:0.13.1-alpine
    ports:
      - "9000:8000"
      - "9001:8001"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
